# rendom sampling numpy

In [3]:
import numpy as np
import random


In [4]:
np.random.random(1)

array([0.72658076])

In [5]:
np.random.random((3,3))

array([[0.57078996, 0.2990332 , 0.16249593],
       [0.48648492, 0.27790186, 0.89594408],
       [0.11588823, 0.34178295, 0.84534199]])

In [8]:
np.random.randint(1,4,(4,4))

array([[1, 2, 3, 2],
       [3, 2, 2, 3],
       [1, 2, 3, 1],
       [3, 2, 1, 2]])

In [9]:
np.random.randint(1,4,(2,4,4))

array([[[3, 2, 2, 1],
        [1, 3, 1, 1],
        [3, 1, 3, 2],
        [3, 3, 1, 1]],

       [[3, 1, 3, 3],
        [1, 3, 2, 2],
        [1, 2, 3, 2],
        [3, 3, 3, 2]]])

In [10]:
np.random.seed(10)
np.random.randint(1,4,(2,4,4))

array([[[2, 2, 1, 1],
        [2, 1, 2, 2],
        [1, 2, 2, 3],
        [1, 2, 1, 3]],

       [[1, 3, 1, 1],
        [1, 3, 1, 3],
        [3, 2, 1, 1],
        [3, 2, 3, 2]]])

In [13]:
np.random.seed(10)
np.random.randint(1,4,(2,4,4))

array([[[2, 2, 1, 1],
        [2, 1, 2, 2],
        [1, 2, 2, 3],
        [1, 2, 1, 3]],

       [[1, 3, 1, 1],
        [1, 3, 1, 3],
        [3, 2, 1, 1],
        [3, 2, 3, 2]]])

In [14]:
2**32-1

4294967295

In [15]:
x=[1,2,3,4]
np.random.choice(x)

2

In [17]:
for i in range(20):
    print(np.random.choice(x))
    

2
4
2
3
2
1
3
3
3
2
1
2
4
2
1
4
3
2
2
3
