# Mathematic Operation Using NumPy


In [1]:
import numpy as np


In [3]:
ar_1=np.arange(1,10).reshape(3,3)
ar_2=np.arange(1,10).reshape(3,3)
print(ar_1)
print(ar_2)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
ar_1+ar_2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [5]:
ar_1-ar_2

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [6]:
ar_1/ar_2

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [7]:
ar_1*ar_2 #for normal multiplication

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [8]:
ar_1 @ ar_2 #for matrix multiplication

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [13]:
ar_1.max()

9

In [14]:
ar_1.argmax() #find the index of max value

8

In [16]:
ar_1.max(axis=0) # tell max number in columb and 1 represent rows

array([7, 8, 9])

you can also use in function same as ax


In [17]:
np.sum(ar_1) #tells sum of all element of matrix

45

In [19]:
np.sum(ar_1,axis=0) #tells sum of all emenemt in columb and same gows with rows but axis will be equal to 1

array([12, 15, 18])

In [20]:
np.mean(ar_1) # ells avarage of array

5.0

In [21]:
np.sqrt(ar_1)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [22]:
np.std(ar_1)

2.581988897471611

In [23]:
np.exp(ar_1)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 2.98095799e+03, 8.10308393e+03]])

In [24]:
np.log(ar_1)

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947],
       [1.94591015, 2.07944154, 2.19722458]])

In [26]:
np.log10(ar_1)

array([[0.        , 0.30103   , 0.47712125],
       [0.60205999, 0.69897   , 0.77815125],
       [0.84509804, 0.90308999, 0.95424251]])