# NumPy function


In [1]:
import numpy as np


# arange()

In [3]:
#np.arange(star,ends,steps)
ar_1d=np.arange(1,13)
print(ar_1d)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [6]:
even_1d=np.arange(0,13,2)
print(even_1d)

[ 0  2  4  6  8 10 12]


# Linespace()

In [9]:
#line_1d=np.linspace(start,end,hw any between balues you required)
line_1d=np.linspace(1,6,3)
print(line_1d)

[1.  3.5 6. ]


# reshape()

In [10]:
ar_2d=ar_1d.reshape(2,6)
print(ar_2d)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [12]:
ar_3d=ar_1d.reshape(2,3,2)
print(ar_3d)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


# ravel()

In [13]:
#convert multi di array in 1d
ar_3d.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

# flatten()

In [14]:
# ravel function and flatter function give similar output that turns multi into 1d array

# transpose()


In [15]:
# help us to convert rows in colou and colums in rows
ar_d=np.array([[1,2],[3,4]])
print(ar_d)

[[1 2]
 [3 4]]


In [16]:
ar_d.transpose()

array([[1, 3],
       [2, 4]])

In [18]:
ar_d.T 
#can also use capital T to transpose the array

array([[1, 3],
       [2, 4]])