In [1]:
import numpy as np

In [2]:
mx_1=np.array([[[1,1,1,],[1,1,1],[1,1,1]]])
print(mx_1)

[[[1 1 1]
  [1 1 1]
  [1 1 1]]]


In [4]:
np.ones(5) #it provide flote datatype by default

array([1., 1., 1., 1., 1.])

In [7]:
mx_1s=np.ones((3,4))
print(mx_1s)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [8]:
mx_2s=np.ones((3,4),dtype=int)
print(mx_1s)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [10]:
mx_2s.dtype

dtype('int32')

In [14]:
mx_0s=np.zeros((4,5))
print(mx_0s)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [18]:
mx_3s=np.empty((7,8),dtype=bool)
print(mx_3s)

[[ True False  True False  True False  True False]
 [ True False  True False  True False  True False]
 [ True False  True False  True False  True False]
 [ True False  True False  True False  True False]
 [ True False  True False  True False  True False]
 [ True False  True False  True False  True False]
 [ True False False False  True False False False]]
